<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="UseCases\NovaPasta\**" />
    <EmbeddedResource Remove="UseCases\NovaPasta\**" />
    <None Remove="UseCases\NovaPasta\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\SchoolManagement.Communication\SchoolManagement.Communication.csproj" />
    <ProjectReference Include="..\..\Shared\SchoolManagement.Exceptions\SchoolManagement.Exceptions.csproj" />
    <ProjectReference Include="..\SchoolManagement.Domain\SchoolManagement.Domain.csproj" />
  </ItemGroup>

</Project>
