// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagement.Infrastructure.DataAcess;

#nullable disable

namespace SchoolManagement.Infrastructure.Migrations
{
    [DbContext(typeof(SchoolManagementDbContext))]
    [Migration("20260514015803_Migration_03")]
    partial class Migration_03
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Boletim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("MatriculaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId")
                        .IsUnique();

                    b.HasIndex("MatriculaId")
                        .IsUnique();

                    b.ToTable("Boletim", (string)null);
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("ProfessorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.HasIndex("ProfessorId");

                    b.ToTable("Disciplinas", (string)null);
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Matricula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("datetime");

                    b.Property<string>("RegistroMatricula")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("RegistroMatricula")
                        .IsUnique();

                    b.HasIndex("TurmaId");

                    b.HasIndex("AlunoId", "TurmaId")
                        .IsUnique();

                    b.ToTable("Matriculas", (string)null);
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.NotasDisciplinaBoletim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BoletimId")
                        .HasColumnType("int");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<double?>("Nota1")
                        .HasColumnType("double");

                    b.Property<double?>("Nota2")
                        .HasColumnType("double");

                    b.Property<double?>("Nota3")
                        .HasColumnType("double");

                    b.Property<double?>("Nota4")
                        .HasColumnType("double");

                    b.Property<int>("SituacaoAlunoDisciplina")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BoletimId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("NotasDisciplinaBoletim");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("Sexo");

                    b.HasKey("Id");

                    b.ToTable("Pessoas", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnoTurma")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("ProfessorId");

                    b.ToTable("Turmas", (string)null);
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Senha");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Aluno", b =>
                {
                    b.HasBaseType("SchoolManagement.Domain.Entities.Pessoa");

                    b.Property<int?>("BoletimId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataMatricula")
                        .HasColumnType("date");

                    b.Property<string>("Matricula")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double?>("MediaFinal")
                        .HasColumnType("double");

                    b.Property<string>("SituacaoAluno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StatusAluno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("TurmaId")
                        .HasColumnType("int");

                    b.Property<string>("Turno")
                        .HasColumnType("longtext");

                    b.HasIndex("BoletimId")
                        .IsUnique();

                    b.HasIndex("TurmaId");

                    b.ToTable("Alunos", (string)null);
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Professor", b =>
                {
                    b.HasBaseType("SchoolManagement.Domain.Entities.Pessoa");

                    b.Property<int>("CargaHorariaSemanal")
                        .HasColumnType("int");

                    b.Property<string>("Titulacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorHora")
                        .HasColumnType("decimal(10,2)");

                    b.ToTable("Professores", (string)null);
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Boletim", b =>
                {
                    b.HasOne("SchoolManagement.Domain.Entities.Matricula", "Matricula")
                        .WithOne("Boletim")
                        .HasForeignKey("SchoolManagement.Domain.Entities.Boletim", "MatriculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matricula");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Disciplina", b =>
                {
                    b.HasOne("SchoolManagement.Domain.Entities.Professor", null)
                        .WithMany("Disciplinas")
                        .HasForeignKey("ProfessorId");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Matricula", b =>
                {
                    b.HasOne("SchoolManagement.Domain.Entities.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagement.Domain.Entities.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.NotasDisciplinaBoletim", b =>
                {
                    b.HasOne("SchoolManagement.Domain.Entities.Boletim", "Boletim")
                        .WithMany("DisciplinasNotas")
                        .HasForeignKey("BoletimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagement.Domain.Entities.Disciplina", "Disciplina")
                        .WithMany()
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boletim");

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Pessoa", b =>
                {
                    b.OwnsOne("SchoolManagement.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("PessoaId")
                                .HasColumnType("int");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Email");

                            b1.HasKey("PessoaId");

                            b1.HasIndex("Valor")
                                .IsUnique();

                            b1.ToTable("Pessoas");

                            b1.WithOwner()
                                .HasForeignKey("PessoaId");
                        });

                    b.OwnsOne("SchoolManagement.Domain.ValueObjects.Nome", "Nome", b1 =>
                        {
                            b1.Property<int>("PessoaId")
                                .HasColumnType("int");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)")
                                .HasColumnName("Nome");

                            b1.HasKey("PessoaId");

                            b1.ToTable("Pessoas");

                            b1.WithOwner()
                                .HasForeignKey("PessoaId");
                        });

                    b.OwnsOne("SchoolManagement.Domain.ValueObjects.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<int>("PessoaId")
                                .HasColumnType("int");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("varchar(11)")
                                .HasColumnName("Cpf");

                            b1.HasKey("PessoaId");

                            b1.HasIndex("Valor")
                                .IsUnique();

                            b1.ToTable("Pessoas");

                            b1.WithOwner()
                                .HasForeignKey("PessoaId");
                        });

                    b.OwnsOne("SchoolManagement.Domain.ValueObjects.DataNascimento", "DataNascimento", b1 =>
                        {
                            b1.Property<int>("PessoaId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("Valor")
                                .HasColumnType("date")
                                .HasColumnName("DataNascimento");

                            b1.HasKey("PessoaId");

                            b1.ToTable("Pessoas");

                            b1.WithOwner()
                                .HasForeignKey("PessoaId");
                        });

                    b.OwnsOne("SchoolManagement.Domain.ValueObjects.Telefone", "Telefone", b1 =>
                        {
                            b1.Property<int>("PessoaId")
                                .HasColumnType("int");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("Telefone");

                            b1.HasKey("PessoaId");

                            b1.ToTable("Pessoas");

                            b1.WithOwner()
                                .HasForeignKey("PessoaId");
                        });

                    b.Navigation("Cpf")
                        .IsRequired();

                    b.Navigation("DataNascimento")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Nome")
                        .IsRequired();

                    b.Navigation("Telefone")
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Turma", b =>
                {
                    b.HasOne("SchoolManagement.Domain.Entities.Professor", null)
                        .WithMany("Turmas")
                        .HasForeignKey("ProfessorId");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Usuario", b =>
                {
                    b.OwnsOne("SchoolManagement.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Email");

                            b1.HasKey("UsuarioId");

                            b1.HasIndex("Valor")
                                .IsUnique();

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("SchoolManagement.Domain.ValueObjects.Nome", "Nome", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("Nome");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Nome")
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Aluno", b =>
                {
                    b.HasOne("SchoolManagement.Domain.Entities.Boletim", "Boletim")
                        .WithOne()
                        .HasForeignKey("SchoolManagement.Domain.Entities.Aluno", "BoletimId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SchoolManagement.Domain.Entities.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("SchoolManagement.Domain.Entities.Aluno", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagement.Domain.Entities.Turma", null)
                        .WithMany("Alunos")
                        .HasForeignKey("TurmaId");

                    b.Navigation("Boletim");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Professor", b =>
                {
                    b.HasOne("SchoolManagement.Domain.Entities.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("SchoolManagement.Domain.Entities.Professor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Boletim", b =>
                {
                    b.Navigation("DisciplinasNotas");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Matricula", b =>
                {
                    b.Navigation("Boletim");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Turma", b =>
                {
                    b.Navigation("Alunos");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Professor", b =>
                {
                    b.Navigation("Disciplinas");

                    b.Navigation("Turmas");
                });
#pragma warning restore 612, 618
        }
    }
}
